{{- if .Values.admin.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patchnotes.fullname" . }}-admin-auth
  labels:
    {{- include "patchnotes.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
type: Opaque
stringData:
  auth: {{ htpasswd .Values.admin.auth.username .Values.admin.auth.password | quote }}
{{- end }}
